unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

set rnu
set nu

set tabstop=4

function! CountWords()
	set laststatus=2
	set statusline=%{wordcount().words}\ words
endfunction

au BufWritePost *.ms silent execute "!groff -ms % -Tpdf > %.pdf" | redraw!

