#!/bin/sh

# Script to get volume/mute status using pamixer

MUTE=$(pamixer --get-mute)
VOL=$(pamixer --get-volume)

if [ $MUTE = 'true' ]; then
	ICON=🔇
elif [ $VOL -lt 34 ]; then
	ICON=🔉
elif [ $VOL -lt 67 ]; then
	ICON=🔉
else
	ICON=🔊
fi

echo "$ICON$VOL"

