#!/bin/bash

# Count number of updates reported from pacman.
# This does NOT poll the servers,
# it just checks the local database.
# 'pacman -Sy' should be run periodically by cron to update this indicator.

count=$(pacman -Qu 2> /dev/null| wc -l)
if [[ $count == 0 ]]
then
	echo ""
else
	echo 📦$count
fi

