#!/bin/sh

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

feh --randomize --bg-fill ~/repos/dotfiles/bg
picom &
polybar laptop &
dunst &
flameshot &
nm-applet &

